Bugfixes
Pepperi-Addons/resource-list pull request #104
Opened 2022-12-15 09:55 UTC by michaelatias

2022-12-20 09:17 UTC, roiaharon-pepperi requested changes

2022-12-20 09:17 UTC, roiaharon-pepperi commented on client-side/src/app/editors/form.ts
> +            // OptionalValues: await this.getResourcesNames(),
why have you changed the DV? isn't there should be a way to select resource on the editor?

2022-12-20 09:17 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/list/list.component.scss
> +    min-height: 20rem;
what will happen in the generic form? the list is not there?

2022-12-20 09:21 UTC, michaelatias commented on client-side/src/app/editors/form.ts
> +            // OptionalValues: await this.getResourcesNames(),
once the editor is created, its should be read only

2022-12-22 07:36 UTC, roiaharon-pepperi approved these changes

2022-12-22 07:37 UTC, merged