Di 22749 menu builder
Pepperi-Addons/resource-list pull request #161
Opened 2023-02-08 08:50 UTC by michaelatias

2023-02-08 12:18 UTC, roiaharon-pepperi commented on cpi-side/events/models/helpers/menu-builder.ts
> +import { ListState } from "../list-state.model";
why is the helpers under model? why aren't them under root?

2023-02-13 08:11 UTC, roiaharon-pepperi requested changes

2023-02-13 08:11 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/menu-builder.ts
> +    private async drawBlocks(menuBlocks: ListMenuBlock[], state: ListState | undefined, changes: Partial<ListState>): Promise<(MenuBlock | null)[]>{
change state to be optional (with '?'), it's more clean approach

2023-02-13 08:11 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/menu-builder.ts
> +    async callDrawBlockFunction(block: ListMenuBlock, state: ListState | undefined, changes: Partial<ListState>): Promise<MenuBlock | null>{
when will this function return null? why not undefined?

2023-02-13 08:11 UTC, roiaharon-pepperi commented on cpi-side/test/events/helpers/menu-builder.spec.ts
> +        it('2. menu blocks function return undefined', async function(){
change the test name

2023-02-13 08:11 UTC, roiaharon-pepperi commented on cpi-side/test/events/helpers/menu-builder.spec.ts
> +import { List } from '../../../models/configuration/list.model';
I don't see that you're running the tests on build. you should add npm script to your package.json to run tests

2023-02-13 09:38 UTC, michaelatias commented on cpi-side/events/helpers/menu-builder.ts
> +    private async drawBlocks(menuBlocks: ListMenuBlock[], state: ListState | undefined, changes: Partial<ListState>): Promise<(MenuBlock | null)[]>{
with ? mark i can only put that in the end of the arguments

2023-02-13 10:31 UTC, roiaharon-pepperi requested changes

2023-02-13 10:31 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/menu-builder.ts
> +    private getDrawFunctionsArray(menuBlocks: ListMenuBlock[]): {AddonUUID: string, DrawURL: string}[]{
the returned value should be exported as a type

2023-02-13 10:31 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/menu-builder.ts
> +        const drawnBlocks = (await this.drawBlocks(drawFunctionsArray, state, changes)).filter(block => block).flat() as MenuBlock[]
why do you need the flat? draw block is returning an array

2023-02-13 12:01 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/menu-builder.ts
> +        const drawnBlocks = (await this.drawBlocks(drawFunctionsArray, state, changes)).filter(block => block).flat() as MenuBlock[]
why would it? what am I missing?

2023-02-15 08:26 UTC, merged