Di 22736 on client load list event
Pepperi-Addons/resource-list pull request #164
Opened 2023-02-15 07:30 UTC by michaelatias

2023-02-16 13:06 UTC, roiaharon-pepperi requested changes
let's discuss on the builders.. I thinks we should have a base abstract class that all the builders inherits from it, and then the interface in united

2023-02-16 13:06 UTC, roiaharon-pepperi commented on cpi-side/events/services/load-list-event.service.ts
> +        if(viewsMenu && viewsMenu.length > 0){
maybe add comment here that the first view is the view selected in the state, because if you won't see what's inside the buildLayout, you won't know that the indexed was played with

2023-02-16 13:06 UTC, roiaharon-pepperi commented on cpi-side/models/events/list-data.model.ts
> +    Items: GridRow[]
why is it GridRow? the view can be something different that grid. RowData is a better name

2023-02-19 09:49 UTC, michaelatias commented on cpi-side/addon-cpi.ts
> +               if(block.Configuration.FieldID == "friends"){
why? this is part of my example

2023-02-19 09:49 UTC, michaelatias commented on addon.config.json
> +  "AddonVersion": "0.9.0",
yes i know i don't know why it was not updated

2023-02-19 09:50 UTC, michaelatias commented on cpi-side/events/helpers/data-builder.ts
> +        const items = await genericResourceService.searchFields(this.list.Resource, searchBody)
thats the function that using search function on generic resource in order to get the fields

2023-02-19 09:51 UTC, michaelatias commented on cpi-side/events/services/event.service.ts
> +    listBuilder!: ListBuilder
because the listBuilder will be initialized only on the build method

2023-02-19 11:01 UTC, michaelatias commented on cpi-side/events/services/grid-view-relation.service.ts
> +        const result =  await pepperi.addons.api.uuid(block.AddonUUID).post({
removed the resource name
i dont think we need that, we can supply the type on the block itself

2023-02-19 12:07 UTC, michaelatias commented on cpi-side/events/services/grid-view-relation.service.ts
> +        const result =  await pepperi.addons.api.uuid(block.AddonUUID).post({
removed the resource name.
about the resource scheme we don't need that, the user can pass any data that he want under the configuration property of the block, if the user want to pass the resource name or the type of that field he can do that

2023-02-26 07:29 UTC, roiaharon-pepperi requested changes

2023-02-26 07:29 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/data-builder.ts
> +        const items = await genericResourceService.searchFields(this.list.Resource, searchBody)
we need a better name.. maybe SearceConfigurationFields or something like that

2023-02-26 07:29 UTC, roiaharon-pepperi commented on cpi-side/models/events/list-data.model.ts
> +    Items: Row[]
Why Row and not DataRow as I suggested? you need the name to reflect what this stands for

2023-02-26 11:50 UTC, michaelatias commented on cpi-side/models/events/list-data.model.ts
> +    Items: Row[]
lets discuss that on the first client side PR, because it have been moved to the shared package

2023-02-26 12:45 UTC, michaelatias commented on cpi-side/events/helpers/data-builder.ts
> +        let queryArray: string[] = []
you can do that with JSONFilter

2023-02-26 12:46 UTC, michaelatias commented on cpi-side/events/helpers/data-builder.ts
> +        if(this.state.SmartSearchQuery && this.state.SmartSearchQuery.length > 0){
lets discuss that on the next pr since the state interface already moved to the shared folder

2023-02-26 13:22 UTC, michaelatias commented on cpi-side/events/helpers/layout-builder.ts
> +        // result.Title = selectedView.Title
no, title configured on the list and not on the view, i removed it

2023-02-26 13:24 UTC, michaelatias commented on cpi-side/events/helpers/layout-builder.ts
> +        const selectedView = views[indexOfSelectedView]
if someone send the specific view he wants to display then we take this view, and put him to be the first view on the views drop down

2023-02-26 13:49 UTC, michaelatias commented on cpi-side/events/helpers/layout-builder.ts
> +        result.Items = createDropDown(views, 'Key', 'Title')
lets discuss about that in the next pr

2023-02-26 13:55 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/data-builder.ts
> +        let queryArray: string[] = []
Who should do it? the AccountUUID is a dynamic filter.. the JSON Filter is for static filters

2023-02-26 16:01 UTC, merged