Di 228882 convert list layout to dataview
Pepperi-Addons/resource-list pull request #173
Opened 2023-03-01 09:40 UTC by michaelatias

2023-03-02 10:19 UTC, roiaharon-pepperi requested changes

2023-03-02 10:19 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.component.ts
> +    const viewBlocksAdapter = new ViewBlocksAdapter(result.Layout.View.ViewBlocks.Blocks)
what should happen is something will be undefined? like the view/viewBlocks?

2023-03-02 10:19 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/list-builder.ts
> +import { List } from "shared"
group to single import

2023-03-02 10:19 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/menu-builder.ts
> + import { ListMenu } from "shared"
group to single import

2023-03-02 10:19 UTC, roiaharon-pepperi commented on cpi-side/events/services/view-relation.service.ts
> +            throw new Error(`in draw blocks - addon with uuid ${block.AddonUUID} inside draw url ${block.DrawURL} doesn't return object of type GridViewOutputData`)
change the error message, the GridViewOutputData is redundant

2023-03-02 10:19 UTC, roiaharon-pepperi commented on shared/entities.ts
> +import { Sorting } from "./models/configuration/sorting.model"
why does it need to file of it's own?

2023-03-02 10:19 UTC, roiaharon-pepperi commented on shared/models/events/list-data.model.ts
> +export interface Row{
why shouldn't you use AddonData? why is the type of the value is not any thing?

2023-03-02 13:56 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/view-blocks-adapter.ts
> +export interface IViewBlocksAdapter{
I will use it in the future in the data source object

2023-03-02 14:05 UTC, michaelatias commented on shared/models/events/list-data.model.ts
> +export interface Row{
Ido said that because generic list doesn't know how to draw array object and so on, then the type will be number | string | boolean | date ...

2023-03-08 06:50 UTC, roiaharon-pepperi approved these changes

2023-03-08 06:50 UTC, merged