Di 22883 convert smart search to menu dataview
Pepperi-Addons/resource-list pull request #179
Opened 2023-03-08 11:51 UTC by michaelatias

2023-03-08 13:51 UTC, roiaharon-pepperi requested changes

2023-03-08 13:51 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/data-source.ts
> +            totalCount: this.items.length,
the total count should be the length of the items only if the search method returned -1 as the count, otherwise you should pass the count returned from the api

2023-03-08 13:51 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/data-source.ts
> +            totalCount: this.items.length,
don't forget to send IncludeCount: true on the search function

2023-03-08 13:51 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/generic-list-adapter.ts
> +            const viewBlocksAdapter = new ViewBlocksAdapter(this.listContainer.Layout.View.ViewBlocks.Blocks)
add ? on the ViewBlocks as well

2023-03-08 13:51 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/generic-list-adapter.ts
> +            return new DataSource(dataview)
aren't the items mandatory as well? what will you do with an empty list?

2023-03-08 13:51 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/view-blocks-adapter.ts
> -    adapt(): BaseDataView
this should be BaseDataView like we discussed on the previous PR

2023-03-08 13:51 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/view-blocks-adapter.ts
>  export class ViewBlocksAdapter implements IViewBlocksAdapter{
GridViewBlockAdapter

2023-03-08 13:51 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/list-ui/list-ui.component.html
> +    [showSearch]="true"
this should come from the configuration

2023-03-08 13:51 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.component.ts
> +  //default dataSource
why aren't you using the DataSource class?

2023-03-12 14:02 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/data-source.ts
> +            totalCount: this.items.length,
yes i've changed that on the next prs

2023-03-12 14:04 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/generic-list-adapter.ts
> +            return new DataSource(dataview)
that code will changed on the next prs, i will no longer create a data source through the adapter

2023-03-13 08:01 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/resource-list/list-ui/list-ui.component.html
> +    [showSearch]="true"
lets discuss that on the data source pr

2023-03-13 08:42 UTC, merged