Di   22884 create menu line menu and buttons
Pepperi-Addons/resource-list pull request #180
Opened 2023-03-08 12:28 UTC by michaelatias

2023-03-08 14:07 UTC, roiaharon-pepperi requested changes

2023-03-08 14:07 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/generic-list-adapter.ts
> +                            handler: async (selectedRows) => this.lineMenuSubject.next({key: block.Key, data: selectedRows})
suppose we have multiple components that registered to the lineMenuSubject, how will it work? you'll emit only the first one

2023-03-08 14:07 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.component.ts
> +import { GVButton } from 'src/app/generic-viewer/generic-viewer.model';
remove this type, you can't reference to anything outside of resource list 0.9 folder,

2023-03-08 14:07 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/generic-list-adapter.ts
> +    constructor(private listContainer: Partial<ListContainer>, private clientEventService: ClientEventsService, private lineMenuSubject: Subject<{key: string, data?: any}>){
why do you need the clientEventService here? the list adapter is not the one emitting events

2023-03-13 08:40 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/generic-list-adapter.ts
> +                            handler: async (selectedRows) => this.lineMenuSubject.next({key: block.Key, data: selectedRows})
will be changed on the future

2023-03-13 09:37 UTC, roiaharon-pepperi requested changes

2023-03-13 09:37 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/generic-list-adapter.ts
>  import { GVButton } from "src/app/generic-viewer/generic-viewer.model";
update this import to point ./metadata

2023-03-13 09:37 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.module.ts
> +    ListUIComponent,
why have you added it?

2023-03-13 09:41 UTC, roiaharon-pepperi approved these changes

2023-03-13 09:41 UTC, merged