Di 23275 change data source implementation
Pepperi-Addons/resource-list pull request #192
Opened 2023-03-30 07:37 UTC by michaelatias

2023-04-03 12:31 UTC, michaelatias commented on cpi-side/events/helpers/utils.ts
> +export function isArrayEquals<T>(arr: T[] | undefined, arr2: T[] | undefined): boolean{
this is going to change there is no need to review that

2023-04-03 12:31 UTC, michaelatias commented on cpi-side/events/helpers/data-builder.ts
> +        return Boolean(this.changes.ListKey != this.state.ListKey || this.changes.ViewKey != this.changes.ViewKey || this.changes.SearchString != this.state.SearchString || isArrayEquals(this.changes
this is going to change there is no need to review that

2023-04-03 12:32 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/smart-filters/json-regular-filters/ngx-filters.ts
> +import { IPepSmartFilterData, IPepSmartFilterDataValue, IPepSmartFilterOperator, IPepSmartFilterOperatorUnit, PepSmartFilterOperatorUnitType } from "@pepperi-addons/ngx-lib/smart-filters";
all the file is going to change there is no need to review that

2023-04-03 12:33 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/smart-filters/json-regular-filters.ts
> +import { IPepSmartFilterData } from "@pepperi-addons/ngx-lib/smart-filters";
all the file is going to change there is no need to review that

2023-04-03 12:33 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/smart-filters/json-regular-filter-factory.ts
> +import { IPepSmartFilterData } from "@pepperi-addons/ngx-lib/smart-filters"
all the file is going to change there is no need to review that

2023-04-04 08:48 UTC, roiaharon-pepperi requested changes

2023-04-04 08:48 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/state-observer.ts
> -    private $searchString: Subject<string> = new Subject()
what is the different between Subject to ReplaySubject?

2023-04-04 08:48 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/view-blocks-adapter.ts
>  export class GridViewBlockAdapter implements IViewBlocksAdapter{
the GridViewAdapter implementation should not be in the same file as the interface & factory

2023-04-04 08:48 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/metadata.ts
> +export function capitalizeFirstLetter(s: string){
why do you need this function? what purpose does it serves?

2023-04-04 08:48 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.component.ts
> +    const container = await this.clientEventService.emitLoadListEvent(undefined,{ListKey: "LIST_KEY", SearchString: 'aa'}) as Required<ListContainer>
why are you emitting this event here and not in the state handler after the generic list init?

2023-04-04 08:48 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.component.ts
> +    .onPageIndexChanged((index => this.pageIndex.next(index)))
why do you need it here?

2023-04-04 09:01 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/layout-observer.ts
> +        if(data.selectionType != undefined){
there is no need I'll remove that

2023-04-09 07:13 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/list-data-source.ts
> +    constructor(private stateChangedHandler: IStateChangedHandler, private isFirstEvent: boolean = true){
in order to identify that the datasource was overridden, and if so there is no need to emit another event

2023-04-09 07:18 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/metadata.ts
> +export function capitalizeFirstLetter(s: string){
thats for the ngx filters to pepperi filters transformer. will be removed after the pr of the pepperi filters will approved.

2023-04-09 09:41 UTC, roiaharon-pepperi requested changes

2023-04-09 09:41 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/pepperi-list.ts
> +        //in case of first init the container already updated
why do I still need the "isFirstEvent" flag?

2023-04-09 09:41 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/state-manager.ts
> +        params.fromIndex = 0
why are you overwriting this? you are breaking your pagination

2023-04-09 09:41 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/state-manager.ts
> +        else if(params.pageIndex != undefined){
you don't need the else, you are ending the function inside the 'if'

2023-04-09 09:41 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/state-manager.ts
> +                pageIndex: Math.floor(((params.toIndex + 1)/ ( (pageSize) || 1))),
not sure this is working.. look on what I did on Resource list 0.7 branch

2023-04-10 10:30 UTC, roiaharon-pepperi approved these changes

2023-04-10 10:30 UTC, merged