Di 23205 client events should get configuration
Pepperi-Addons/resource-list pull request #193
Opened 2023-03-30 07:39 UTC by michaelatias

2023-04-04 10:44 UTC, roiaharon-pepperi requested changes

2023-04-04 10:44 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/pepperi-list.ts
> +        console.log('menu clicked!!')
why is this not implemented?

2023-04-04 10:44 UTC, roiaharon-pepperi commented on cpi-side/events/contorllers/load-list.controller.ts
> +            if(!changes || !changes.ListKey){
you need to check for the list as well, if the list exist, why do you need it's key?

2023-04-04 10:44 UTC, roiaharon-pepperi commented on cpi-side/events/contorllers/menu-click.controller.ts
> +            throw Error(`error inside onClientMenuClick event: ${err}`)
writing ${err} inside the string template will execute toString on the object, which result in [object][object]. you should call JSON.stringify on the err

2023-04-04 10:44 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/data-builder.ts
> +        return Boolean(this.changes.ListKey != this.state.ListKey || this.changes.ViewKey != this.changes.ViewKey || this.changes.SearchString != this.state.SearchString || isArrayEquals(this.changes
why do you need the Boolean conversion? 
isArrayEqual can be replaced with isEqual from loadash

2023-04-04 10:44 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/utils.ts
> +export function isArrayEquals<T>(arr: T[] | undefined, arr2: T[] | undefined): boolean{
it's best that you use some package to check it.. I would recommend isEqual by loadash

2023-04-04 10:44 UTC, roiaharon-pepperi commented on cpi-side/events/services/load-list-event.service.ts
> +        const list = listConfiguration || await service.getList(changes.ListKey)
I would replace it with a ternary to avoid confusion.. 
listConfiguration ? listConfiguration : await service.getList(changes.listKey

2023-04-09 09:30 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/pepperi-list.ts
> +        console.log('menu clicked!!')
thats irrelevant and will changed on the next prs

2023-04-10 14:14 UTC, roiaharon-pepperi approved these changes

2023-04-10 14:34 UTC, merged