Di 23315 handover qa
Pepperi-Addons/resource-list pull request #196
Opened 2023-03-30 07:45 UTC by michaelatias

2023-04-10 15:49 UTC, roiaharon-pepperi requested changes

2023-04-10 15:49 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/pepperi-list.ts
> +        return stateSelectionType != listSelectionType || !_.isEqual(stateSelectedItems, listSelectedItems)
I'm not sure I understand this line.. stateSelectionType is a boolean, so does listSelectionType.
but stateSelectionType & listSelectionType does not contain the same boolean

2023-04-10 15:49 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/pepperi-list.ts
> +                SelectAll: data.selectionType == 0,
the way to know if the SelectAll is "On", is to check whether the selectionType is 'Multiple'? this doesn't seem right.. what am I missing?

2023-04-10 15:49 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/helpers/state-manager.ts
> +    private isSmartSearchChanged(listSmartSearch: JSONRegularFilter[], stateSmartSearch: JSONRegularFilter[]){
can't this be replaced with _isEqual function of loadash?

2023-04-10 15:49 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/list-ui/list-ui.component.ts
> +  @Input() $searchString: ReplaySubject<string>
remove $ from the param name..

2023-04-10 15:49 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.component.ts
> +    this.pepperiList = new PepperiList(this.clientEventService, {ListKey: "LIST_KEY", SearchString: 'aa'}, this.list1)
what will happen when you send both state & list configuration?

2023-04-10 15:49 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.component.ts
> +  $pageIndex: ReplaySubject<number> = new ReplaySubject()
why are you adding $ sign to the parameters names? please remove it

2023-04-10 15:49 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/services/resources.service.ts
this file will be removed on future versions?

2023-04-10 15:49 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/data-builder.ts
> +        //we should always ask for key also
what happens if the view already has the key? will you add it twice?

2023-04-11 10:06 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.component.ts
> +    this.pepperiList = new PepperiList(this.clientEventService, {ListKey: "LIST_KEY", SearchString: 'aa'}, this.list1)
the list replacing the list that "in the DB", so everything will works as before, but instead of getting the list configuration from the db it gets the list configuration  as a parameter

2023-04-11 10:07 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/resource-list/resource-list.component.ts
> +  $pageIndex: ReplaySubject<number> = new ReplaySubject()
convention for subjects

2023-04-11 10:07 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/resource-list/list-ui/list-ui.component.ts
> +  @Input() $searchString: ReplaySubject<string>
convention for subjects

2023-04-11 10:10 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/services/resources.service.ts
yes

2023-04-11 10:18 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/pepperi-list.ts
> +                SelectAll: data.selectionType == 0,
with the debuggerI saw that if I'm selecting all then data.selectionType is 0, otherwise its 1

2023-04-11 10:44 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/pepperi-list.ts
> +        return stateSelectionType != listSelectionType || !_.isEqual(stateSelectedItems, listSelectedItems)
this function check if something changed with the selected lines.
the selected lines have change if the current selected items are different than the state selected items, **or that the current selection type is different than the state selection type.**

2023-04-16 11:28 UTC, roiaharon-pepperi approved these changes

2023-04-16 11:28 UTC, merged