Di 23203 create list abi
Pepperi-Addons/resource-list pull request #197
Opened 2023-03-30 08:13 UTC by michaelatias

2023-04-10 15:59 UTC, roiaharon-pepperi requested changes

2023-04-13 09:30 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/list-page-block/list-page-block.component.ts
but right now i have no other way to test it

2023-04-13 09:31 UTC, michaelatias commented on server-side/installation.ts
> +    const listABIName = "ListABI"
we didn't agree on any name, I'll change it to List

2023-04-13 09:31 UTC, michaelatias commented on server-side/installation.ts
> +    const listABIName = "ListABI"
we didn't agree on a name

2023-04-16 12:08 UTC, roiaharon-pepperi approved these changes

2023-04-16 12:08 UTC, merged