Resource picker and display list on block
Pepperi-Addons/resource-list pull request #2
Opened 2022-03-22 11:25 UTC by michaelatias

2022-03-30 09:26 UTC, roiaharon-pepperi requested changes

2022-03-30 09:26 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.ts
> +        this.blockEditorService.pluginUUID = "0e2ae61b-a26a-4c26-81fe-13bdd2e4aaa3"
please change it. it should come from the hostObject.

2022-03-30 09:26 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.ts
> +    resourcesNames:  {key:string, value:string}[] = []
there is a keyValuePair object in ngx-lib, see if you can use it instead

2022-03-30 09:26 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.module.ts
> +        TranslateService
why do you need the TranslateService in here? isn't the TranslateStore enough?

2022-03-30 09:26 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +    async init(params: { searchString?: string; filter?: any; sorting?: IPepListSortingChangeEvent; fromIndex: number; toIndex: number; }): Promise<IPepGenericListInitData> {
don't you have a type to define? this is how Yaron is exposing it from the composite-lib?

2022-03-30 09:26 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +                  FieldID: 'CreationDateTime',
dates should be of type 'DateAndTime'

2022-03-30 09:26 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +        this.blockService.pluginUUID = "0e2ae61b-a26a-4c26-81fe-13bdd2e4aaa3"
again, this should come from the hostObject

2022-03-30 09:26 UTC, roiaharon-pepperi commented on server-side/api.ts
> +export async function get_all_collections(client: Client, request: Request){
as of now, you are only displaying UDC collections. But in the future, this addon will serve all types of resources. try to create a more generic function? something like get_list_of_resources? and get the resource type as a query parameter

2022-03-30 09:26 UTC, roiaharon-pepperi commented on server-side/my.service.ts
> +    getAllUDCCollections(): Promise<any>{
you can use papi-sdk. there is a 'user_defined_collections' object. install the latest version

2022-03-30 09:40 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.html
> +<mat-tab-group #tabgroutp class="editor-tabs">
why do you need the tabs if you only have one tab?

2022-04-05 09:37 UTC, michaelatias commented on client-side/src/app/block/block.component.ts
> +    async init(params: { searchString?: string; filter?: any; sorting?: IPepListSortingChangeEvent; fromIndex: number; toIndex: number; }): Promise<IPepGenericListInitData> {
this is how Yaron exposing it

2022-04-05 09:39 UTC, michaelatias commented on client-side/src/app/block-editor/block-editor.component.ts
> +        this.blockEditorService.pluginUUID = "0e2ae61b-a26a-4c26-81fe-13bdd2e4aaa3"
the host object does not contains the addon uuid, i will put the addon uuid in constant on another file

2022-04-05 09:40 UTC, michaelatias commented on client-side/src/app/block/block.component.ts
> +                  FieldID: 'CreationDateTime',
thats temporary code

2022-04-05 09:59 UTC, michaelatias commented on client-side/src/app/block-editor/block-editor.component.html
> +<mat-tab-group #tabgroutp class="editor-tabs">
in the next sprint there will be another tab

2022-04-05 15:23 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.ts
> +        this.blockEditorService.pluginUUID = "0e2ae61b-a26a-4c26-81fe-13bdd2e4aaa3"
so I think that you should open a feature for tomer to add it. as it comes from the hostObject in the ATD Editor, it should come here as well

2022-04-05 15:24 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +    async init(params: { searchString?: string; filter?: any; sorting?: IPepListSortingChangeEvent; fromIndex: number; toIndex: number; }): Promise<IPepGenericListInitData> {
consider talking to him about it, this should be a type somewhere in the lib

2022-04-13 09:08 UTC, closed without merging