Save cancel button in form
Pepperi-Addons/resource-list pull request #21
Opened 2022-05-01 06:43 UTC by michaelatias

2022-05-01 10:31 UTC, roiaharon-pepperi requested changes

2022-05-01 10:31 UTC, roiaharon-pepperi commented on client-side/src/app/resource-map.ts
> +            ReadOnly : false
are you enabling inline editing is the list?

2022-05-01 10:52 UTC, michaelatias commented on client-side/src/app/data-configuration-block/data-configuration-block.component.scss
> +.buttons{
i've tried to add pep-spacing-element as a class for both buttons, the result is that one button seat above the other button, and i want them to seat next to each other(in the same line)

2022-05-01 10:53 UTC, michaelatias commented on client-side/src/app/resource-map.ts
> +            ReadOnly : false
yes, and when the user click on the save button i will send post request to the udc.

2022-05-01 10:55 UTC, roiaharon-pepperi commented on client-side/src/app/resource-map.ts
> +            ReadOnly : false
but It's not working for all the fields. is it OK by the product? did you checked it?

2022-05-01 10:56 UTC, roiaharon-pepperi commented on client-side/src/app/data-configuration-block/data-configuration-block.component.scss
> +.buttons{
it's because you need to give it display:flex. you can see the implementation of the buttons in the dialog component

2022-05-02 08:36 UTC, roiaharon-pepperi approved these changes

2022-05-02 08:36 UTC, merged