Di 24127 error handling
Pepperi-Addons/resource-list pull request #238
Opened 2023-06-19 12:34 UTC by michaelatias

2023-06-20 06:08 UTC, roiaharon-pepperi requested changes

2023-06-20 06:08 UTC, roiaharon-pepperi commented on cpi-side/addon-cpi.ts
you should not change the interface of the Client Actions. maybe add error message on the listContainer interface and write it the in case of an error..
In addition, the error should be more meaning full (list not found, view not found etc...)

2023-06-20 06:08 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/services/client-events.service.ts
> +            throw Error(result.error)
@Chasky-H proposed an idea to combine the error message in the empty list message, this is a good idea I think. throwing the error wouldn't do you any good because no one is catching it.. 
you should show the error to the user, let him know what went wrong

2023-06-21 07:23 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/services/client-events.service.ts
> +            throw Error(result.error)
the meaning of that is to change the error msg in runtime.
ngx lib probably do not support that, but i can reload the list, i don't think its a good idea i think it will be better if i'll display a dialog instead.

2023-06-21 08:27 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/services/client-events.service.ts
> +            throw Error(result.error)
if you'll check the empty message and doesn't return items, that it should be fine.. I'm doing it all the time

2023-06-28 06:06 UTC, roiaharon-pepperi requested changes
just realize that I didn't see anywhere in you code that you're unsubscribing from all the subjects. please do it, as it can cause memory leaks

2023-06-28 06:06 UTC, roiaharon-pepperi commented on client-side/src/app/resource-list-0.9/resource-list/list-ui/list-ui.component.ts
> +  emptyState: IPepGenericListEmptyState = {title: '', description: '', show: true}
why is it true by default? why not change is to 'true' only when the subject of the errorMsg is called?

2023-06-28 06:06 UTC, roiaharon-pepperi commented on cpi-side/events/helpers/menu-builder.ts
> +            throw Error(`can't draw  menu blocks for adddon uuid ${drawURL.AddonUUID} and url ${drawURL.DrawURL}`)
haven't we said you're not suppose to throw exception if the draw functions were not succeeded? please replace it with console.error.
not having a menu is not a reason not to draw the list

2023-06-29 06:24 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/helpers/pepperi-list.ts
> +            result =  await this.clientEventsService.emitStateChangedEvent(this.listContainer.State, changes, this.listContainer.List) || {}
I'm updating the list container later on

2023-06-29 06:28 UTC, michaelatias commented on client-side/src/app/resource-list-0.9/resource-list/list-ui/list-ui.component.ts
> +  emptyState: IPepGenericListEmptyState = {title: '', description: '', show: true}
in order to display an empty state (by default we are displaying the empty state if there is no items)

2023-06-29 07:25 UTC, roiaharon-pepperi approved these changes

2023-06-29 07:31 UTC, merged