Editor open mode
Pepperi-Addons/resource-list pull request #24
Opened 2022-05-08 09:33 UTC by michaelatias

2022-05-08 10:59 UTC, roiaharon-pepperi requested changes

2022-05-08 10:59 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.html
> +            <pep-select
no need for the mandatory check. you can set it to always true. when it's not disabled, it will be mandatory

2022-05-08 10:59 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.ts
> +    onAllowEditChange($event){
remove all these functions. use 2 way binding, and call update function directly

2022-05-08 10:59 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +                        const queryParams: Params = {
delete the variables and call the function with the parameters instead of the variable.

2022-05-08 10:59 UTC, roiaharon-pepperi commented on client-side/src/app/data-configuration-block-editor/data-configuration-block-editor.component.ts
> +    onMinHeightChange($event){
remove these function and use 2 way binding

2022-05-08 10:59 UTC, roiaharon-pepperi commented on client-side/src/app/services/slugs-service.ts
> +    get papiClient(): PapiClient {
create a utilities service which will hold the papi client. no need to have more that 1 papi client instance

2022-05-09 11:08 UTC, roiaharon-pepperi requested changes

2022-05-09 11:08 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.ts
> -    }
remove the comments from the code

2022-05-09 11:08 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.ts
> +        const slugs = await this.utilitiesService.getSlugs()
why did you put the getSlugs function in the utilities service?

2022-05-09 11:08 UTC, roiaharon-pepperi commented on client-side/src/app/data-configuration-block-editor/data-configuration-block-editor.component.ts
> +    // onMinHeightChange($event){
remove comments

2022-05-09 11:08 UTC, roiaharon-pepperi commented on client-side/src/app/data-configuration-block/data-configuration-block.component.ts
> +      debugger
remove debugger

2022-05-09 11:08 UTC, roiaharon-pepperi commented on client-side/src/app/services/utilities-service.ts
> +export class UtilitiesService{
why renaming the SlugsService? I meant for you to create another service called utilities who will be used inside both udcService and SlugsService

2022-05-09 12:07 UTC, michaelatias commented on client-side/src/app/block-editor/block-editor.component.ts
> +        const slugs = await this.utilitiesService.getSlugs()
because getSlugs will be the only "slugs" function i will need, so i thought that its better to just add this function in utilities.

2022-05-09 12:10 UTC, michaelatias commented on client-side/src/app/services/utilities-service.ts
> +export class UtilitiesService{
same as previous note.
because getSlugs will be the only "slugs" function i will need, so i thought that its better to just add this function in utilities.

2022-05-10 12:00 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.ts
> +        const slugs = await this.utilitiesService.getSlugs()
ok. no problems.

2022-05-10 12:01 UTC, merged