Data view grid title
Pepperi-Addons/resource-list pull request #3
Opened 2022-03-24 09:21 UTC by michaelatias

2022-03-30 09:37 UTC, roiaharon-pepperi requested changes

2022-03-30 09:37 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.ts
> +        this.hostEvents.emit({
this is the way to work with the block editor? for each change you are populate an event? why don't you have a save button where you populate this event only once?

2022-03-30 09:37 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.html
> +        label="text"
didn't you mean 'Title' on the label?

2022-04-05 11:05 UTC, michaelatias commented on client-side/src/app/block-editor/block-editor.component.ts
> +        this.hostEvents.emit({
temporary code will change in the future

2022-04-13 09:08 UTC, closed without merging