Di 20297 editors api
Pepperi-Addons/resource-list pull request #39
Opened 2022-06-08 14:21 UTC by michaelatias

2022-06-13 09:02 UTC, roiaharon-pepperi commented on server-side/views.service.ts
> +            editor.Key = uuidv4()
you don't need it. ADAL is doing it for you

2022-06-13 09:02 UTC, roiaharon-pepperi commented on shared/entities.ts
> +export type OpenMode = Popup | SamePage
why do you save it in a variable? replace with 
export type OpenMode = 'popup' | 'same-page'

2022-06-16 08:16 UTC, michaelatias commented on client-side/src/app/app.route.ts
> +            {
yes it works, anyway I've changed the order, It makes more sense

2022-06-22 06:05 UTC, roiaharon-pepperi requested changes

2022-06-22 06:05 UTC, roiaharon-pepperi commented on server-side/views.service.ts
> +    async getEditors(options){
you have 3 pair of functions (get, post, create) that does the same logic but on a different table. merge them and send the table name as a parameter

2022-06-22 06:11 UTC, michaelatias commented on client-side/src/app/views-and-editors/views-and-editors.component.html
> +    <mat-tab label= "{{'TABS.VIEWS' | translate}}">
but this is how we always refer to strings inside the en.json file?

2022-06-22 06:12 UTC, michaelatias commented on client-side/src/app/views-and-editors/views-and-editors.component.ts
> +  private widthArray = [
the width is relative, so if all the items get width:0 then they all will be with the same width

2022-06-22 06:14 UTC, michaelatias commented on server-side/views.service.ts
> +    async getEditors(options){
you right, i did it in the current branch that im now working on, so it will be like you said in the future

2022-06-22 06:25 UTC, roiaharon-pepperi commented on client-side/src/app/views-and-editors/views-and-editors.component.html
> +    <mat-tab label= "{{'TABS.VIEWS' | translate}}">
no, it's not. double brackets means that this will be transpiled on the server side. here you don't need it because you have the 'translate' pipe which does it for you. you can look at the UDC code and see

2022-06-22 07:18 UTC, roiaharon-pepperi commented on client-side/src/app/views-and-editors/views-and-editors.component.ts
> +  private widthArray = [
leave a comment do it will be more clear

2022-06-22 08:56 UTC, roiaharon-pepperi requested changes

2022-06-22 08:56 UTC, roiaharon-pepperi commented on client-side/src/app/views-editor/views-editor.component.html
> +    <mat-tab label= "Tabs.General' | translate">
you're missing the opening single quote sign. also, there are double brackets on the value of the button, remove them please

2022-06-22 11:34 UTC, roiaharon-pepperi approved these changes

2022-06-22 11:34 UTC, merged