Allow data import export
Pepperi-Addons/resource-list pull request #4
Opened 2022-03-27 14:24 UTC by michaelatias

FYI generic list could not be updated after import action because dimx import function returning a void so i don't know when the import action was completed .

2022-03-30 09:57 UTC, roiaharon-pepperi requested changes

2022-03-30 09:57 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.html
> +<pep-dimx #dimx [DIMXAddonUUID]="'122c0e9d-c240-4865-b446-f37ece866c22'" [DIMXResource]="resource" (DIMXProcessDone)='onDIMXProcessDone($event);'></pep-dimx>
the addon uuid should come from a const. any how this create a forbidden decoupling from the resource list to the UDC, @Chasky-H what do you think of this? should you hold another addon uuid inside your addon? maybe this need to come from a relation or something?

2022-03-30 09:57 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +      this.allowExport = Boolean(this.hostObject.configuration.allowExport)
you should add '|| false' to protect yourself against undefined configuration

2022-03-30 09:57 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +      debugger
remove debugger

2022-03-30 09:57 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +            OwnerID: "122c0e9d-c240-4865-b446-f37ece866c22"
again, this should be a const somewhere

2022-03-30 09:57 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +      const downloadURL = $event[0]?.ReturnedObject?.DownloadURL
I don't like this check, we need to discuss it. maybe add a type on the event object?

2022-03-30 09:57 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +    getMenuItems() {
what happens if both menu items are hidden? menu will be hidden as well? if not, you should hide it

2022-03-30 09:57 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +    setItems(items:any[]){
I don't see where you call this function? is it neccesary?

2022-03-30 12:13 UTC, michaelatias commented on client-side/src/app/block-editor/block-editor.component.html
> -Block editor works...
there will be another tab in the next pull request

2022-03-30 15:08 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +      this.allowExport = Boolean(this.hostObject.configuration.allowExport)
are you sure it won't throw exception 'Cannot read property alllowExport of undefined?

2022-03-30 16:07 UTC, Chasky-H commented on client-side/src/app/block/block.component.html
> +<pep-dimx #dimx [DIMXAddonUUID]="'122c0e9d-c240-4865-b446-f37ece866c22'" [DIMXResource]="resource" (DIMXProcessDone)='onDIMXProcessDone($event);'></pep-dimx>
For now, let's create a const somewhere.
We will need to solve this when this addon will support resources no in the UDC.

2022-04-05 07:42 UTC, Chasky-H commented on client-side/src/app/block/block.component.ts
> +      const downloadURL = $event[0]?.ReturnedObject?.DownloadURL
the DIMX component might change in the future. for now let's leave this here

2022-04-05 07:45 UTC, Chasky-H commented on client-side/src/app/block/block.component.ts
> +      this.allowExport = Boolean(this.hostObject.configuration.allowExport)
You are doing the nullity check for the configuration in the `ngOnChanges` but not here
It seems that both functions are doing pretty much the same, consider combining

2022-04-05 11:09 UTC, michaelatias commented on client-side/src/app/block/block.component.ts
> +      this.allowExport = Boolean(this.hostObject.configuration.allowExport)
i add a null checking, because i changes the structure of the ngoninit and ngonchanges, i will combine it in the next pull request

2022-04-05 15:19 UTC, roiaharon-pepperi approved these changes

2022-04-05 15:19 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +import { UDCUUID } from '../addon.config';
you can add 'config' here as well instead of importing him of a different line

2022-04-05 15:19 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +      debugger
debugger is still here

2022-04-05 15:19 UTC, roiaharon-pepperi commented on server-side/my.service.ts
> +        return this.papiClient.get(`/user_defined_collections/${collectionName}`)
you should replace this for using papiClient as well

2022-04-12 12:16 UTC, merged