Di 20298 editors editor general tab
Pepperi-Addons/resource-list pull request #40
Opened 2022-06-23 08:45 UTC by michaelatias

2022-06-26 12:00 UTC, roiaharon-pepperi requested changes

2022-06-26 12:00 UTC, roiaharon-pepperi commented on client-side/src/app/views-editor/views-editor.component.ts
> +    this.location.back()
why have you changed it to work with location?

2022-06-27 06:17 UTC, michaelatias commented on client-side/src/app/views-editor/views-editor.component.ts
> +    this.location.back()
no idea why I changed it, cant remember why. I guess by mistake

2022-06-27 10:20 UTC, michaelatias commented on client-side/src/app/editors-form/editors-form.component.html
> +<div class="header">
no idea how pep top bar will help me with buttons, I looked for example but couldn't find out.

2022-06-27 10:46 UTC, michaelatias commented on client-side/src/app/editors/view-editor.ts
> +      if(key === "new"){
deprecated

2022-06-27 12:34 UTC, roiaharon-pepperi approved these changes

2022-06-27 12:34 UTC, roiaharon-pepperi commented on client-side/src/app/editors-form/editors-form.component.scss
>      float: right;
do you still need this css after you replaced the HTML?

2022-06-27 12:34 UTC, roiaharon-pepperi commented on client-side/src/assets/i18n/en.json
> +    "Same-page": "replace the current page",
change 'Same-page' to 'Same_Page'

2022-06-27 12:34 UTC, merged