Di 20624 align UI to prd updated
Pepperi-Addons/resource-list pull request #45
Opened 2022-07-25 08:04 UTC by michaelatias

2022-07-25 12:23 UTC, roiaharon-pepperi requested changes

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/app/draggable-card-fields/draggable-card-fields.module.ts
> +import { MatButtonModule } from '@angular/material/button';
why do you need these imports? I don't see that you are using them

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/app/services/editors.service.ts
> +        private router: Router
why do you need the Router? where do you use it?

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/app/views-and-editors/table/table.component.ts
> +  itemsLoaded:boolean = false;
remove this

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/app/views-and-editors/table/table.component.ts
> +      this.router.navigate([`${this.editRoute}${value.Key}`], { relativeTo: this.route })
what will happen if you will not pass a value?

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/app/views-and-editors/views-and-editors.component.html
> +                    *ngIf="currentTab == 0"
change to 'currentTabIndex'

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/app/views-and-editors/views-and-editors.component.ts
> +  currentTab: 0 | 1 = 0
when you'll add a new tab this will crash. change to number

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/app/views-and-editors/views-and-editors.component.ts
> +  // @ViewChild('tabgroup', {read: MatTabGroup}) set tabGroup(element)
remove comment

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/app/views-and-editors/views-and-editors.component.ts
> +import { AfterViewInit, Component, OnInit, ViewChild } from '@angular/core';
remove redundant imports

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/app/views-form/views-form.component.ts
> +    const dataMsg = new PepDialogData({
this is the second place you are implementing this function. move it to the utilities service

2022-07-25 12:23 UTC, roiaharon-pepperi commented on client-side/src/assets/i18n/en.json
> -    "Resource": "Resource"
there is a lot of mess in this file. please decide on 1 naming convention and change all accordingly

2022-07-25 12:42 UTC, michaelatias commented on client-side/src/app/views-and-editors/views-and-editors.component.ts
> +  currentTab: 0 | 1 = 0
i think this is better for now, because  right now we have only indexes 0,1 available so that's the right type for now, if we will add more tabs in the future we will need to update the tab of the currentIndex

2022-07-26 07:18 UTC, michaelatias commented on client-side/src/app/views-form/views-form.component.ts
> +    const dataMsg = new PepDialogData({
I've tried what you said and there is an error because of that. lets discuss about that

2022-07-27 06:21 UTC, roiaharon-pepperi requested changes

2022-07-27 06:21 UTC, roiaharon-pepperi commented on client-side/src/app/services/utilities-service.ts
> +import { TranslateService } from "@ngx-translate/core";
remove redundant imports

2022-07-27 08:24 UTC, roiaharon-pepperi approved these changes

2022-07-27 08:24 UTC, merged