Di 19780 add cancel and save buttons to editor block
Pepperi-Addons/resource-list pull request #46
Opened 2022-07-26 06:59 UTC by michaelatias

2022-07-28 08:36 UTC, roiaharon-pepperi requested changes

2022-07-28 08:36 UTC, roiaharon-pepperi commented on client-side/src/app/block-editor/block-editor.component.ts
> +            this.resource = this.resource ||  (this.resourcesNames.length > 0? this.resourcesNames[0].value : undefined)
why did you add parentheses? the logic is unclear and I think you have a bug

2022-07-28 08:36 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +    // resourceName: string
remove comment

2022-07-28 08:36 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +            if(this.editorDataView){
if there is no 'else' why did you split the if statement?

2022-07-28 11:41 UTC, michaelatias commented on client-side/src/app/block-editor/block-editor.component.ts
> +            this.resource = this.resource ||  (this.resourcesNames.length > 0? this.resourcesNames[0].value : undefined)
i didnt add any logic, i just add the brackets because the js always compute the right side of the || without the bracket.

2022-07-28 11:45 UTC, michaelatias commented on client-side/src/app/block/block.component.ts
> +            if(this.editorDataView){
thats because if i have editor data view i need to add the edit action, and always when 1 row is selected i need to add the delete action

2022-07-31 08:09 UTC, roiaharon-pepperi approved these changes

2022-07-31 08:10 UTC, merged