Di 21011 data editor support reference fields
Pepperi-Addons/resource-list pull request #57
Opened 2022-08-25 09:49 UTC by michaelatias

2022-09-06 09:57 UTC, roiaharon-pepperi requested changes

2022-09-06 09:57 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +    const fieldIDOfResourceToOpen = Object.keys(currentResource.Fields).find(fieldID => fieldID == field)
if the field doesn't exist on the resource than it will crush

2022-09-06 09:57 UTC, roiaharon-pepperi commented on client-side/src/app/services/generic-resource-service.ts
> +    async getItemFromResourceByKey(resourceName: string, key: string){
there should be a function to get an item by it's key. please check

2022-09-07 11:12 UTC, michaelatias commented on client-side/src/app/services/generic-resource-service.ts
> +    async getItemFromResourceByKey(resourceName: string, key: string){
removed, I'm not using this function anyway

2022-09-07 12:05 UTC, roiaharon-pepperi approved these changes

2022-09-07 12:06 UTC, merged