Di 21396 resource viewer performance
Pepperi-Addons/resource-list pull request #67
Opened 2022-10-24 14:42 UTC by michaelatias

2022-10-24 14:49 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +    const configuration = {
Why didn't you add a new type for this configuration? is this the only place it used?

2022-10-24 14:50 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/generic-viewer.component.html
> +            [value]="genericViewer.view.Key"
please add a fallback in case the genericViewer is undefined

2022-10-24 15:02 UTC, roiaharon-pepperi commented on client-side/src/app/resource-selection/resource-selection.component.ts
> +    this.configurationObj = await this.createGenericViewerConfiguration()
move it to the ngOnInit function and use .then() on the promise

2022-10-24 15:05 UTC, roiaharon-pepperi commented on client-side/src/app/services/generic-resource-service.ts
> +    async getGenericView(viewKey: string){
why are you using pepHttp and not papiSdk? please switch to papiSdk to avoid writing the url hard coded

2022-10-24 15:12 UTC, roiaharon-pepperi commented on server-side/services/generic-viewer.service.ts
> +            [view] = await viewsService.getItems({where: `Key="${key}"`}) as View[];
don't you have getByKey function that will return onlu 1 item? why are you switching between single obj to array?

2022-10-24 15:14 UTC, roiaharon-pepperi commented on server-side/services/generic-viewer.service.ts
> +        const [dataview] = await dataViewService.getDataView(`GV_${dataViewKey}_View`) as GridDataView[]
same as here, why are you using it as an array?

2022-10-24 15:17 UTC, roiaharon-pepperi requested changes
please move through comments and fix them

2022-10-25 06:40 UTC, michaelatias commented on client-side/src/app/field-editor/field-editor.component.ts
> +    const configuration = {
this is the only place i use object of that type

2022-10-25 06:41 UTC, michaelatias commented on client-side/src/app/generic-viewer/generic-viewer.component.html
> +            [value]="genericViewer.view.Key"
if the ngIf is true, so there is no way that the generic viewer or its view will be undefined

2022-10-25 08:15 UTC, michaelatias commented on server-side/services/generic-viewer.service.ts
> +    addonService: AddonService = new AddonService(this.client)
removed

2022-10-25 08:17 UTC, michaelatias commented on server-side/services/generic-viewer.service.ts
> +            [view] = await viewsService.getItems({where: `Key="${key}"`}) as View[];
I dont have such function, I dont replace between single object to array I always get an array so I use destruction  in order to get rid of the array(dataview will always be the first element of the array)

2022-10-25 08:18 UTC, michaelatias commented on server-side/services/generic-viewer.service.ts
> +        const [dataview] = await dataViewService.getDataView(`GV_${dataViewKey}_View`) as GridDataView[]
same as the previoud answer

2022-10-25 08:42 UTC, roiaharon-pepperi commented on client-side/src/app/services/generic-resource-service.ts
> +    async getGenericView(viewKey: string){
and what will happen if you get empty array? or undefined? will it crash?

2022-10-25 08:57 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +    const configuration = {
it's more clean for the 'genericViewer' to be a part of the configurationObj

2022-10-25 09:04 UTC, roiaharon-pepperi commented on server-side/services/generic-viewer.service.ts
> +            [view] = await viewsService.getItems({where: `Key="${key}"`}) as View[];
Expose an new function that will get an Item by the Key to avoid filtering by Key

2022-10-25 09:04 UTC, roiaharon-pepperi commented on server-side/services/generic-viewer.service.ts
> +        const [dataview] = await dataViewService.getDataView(`GV_${dataViewKey}_View`) as GridDataView[]
same as previous

2022-10-25 13:04 UTC, roiaharon-pepperi approved these changes

2022-10-25 13:04 UTC, merged