Di 21010 basic array fields on editor
Pepperi-Addons/resource-list pull request #77
Opened 2022-11-03 12:37 UTC by michaelatias

2022-11-06 06:59 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-add-form/primitive-array-add-form.component.html
> +<pep-generic-form [dataSource]="dataSource" [dataView]="dataView">
Why do you need the overhead of the form for a single textbox?

2022-11-06 07:11 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +    this.loadCompleted = true
why do you need the loadComplete variable? there is no async operation here

2022-11-06 07:24 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +    return this.configurationObject.Array.map((val, index) => {
what is the type for configurationObject? if it's an array than why aren't you defining is as such?

2022-11-06 09:19 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +        const castingMap = new CastingMap()
Why are you casting the object here? why don't cast it only when sending to the server? in addition, you need to do it also on edit

2022-11-06 12:01 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +    this.openFormDialog(item, (value => { this.editArrayItem(value, Number(item.Index))}))
you need to check if item is not undefined, otherwise the object will change on 'cancel' as well

2022-11-06 12:03 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +    this.configurationObject.Array[index] = newItem
you need to check if the index is not larger than the length of the array

2022-11-06 12:06 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +  pushSingleLineActions(actions: any[]){
you don't need to pass the array. change this function to return the actions. and push the items to the array on the caller.

2022-11-06 12:11 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +  @Input() editorDataSource: any
why do you need the this input? I don't see you are using it

2022-11-06 12:12 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/array-fields.component.ts
> +  @Input() dataSource: any
why do you need the dataSource? I don't see that you are using it, just passing it the primitive array

2022-11-06 12:22 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +import { map } from 'rxjs';
where do you use these? aren't they redundant?

2022-11-06 12:29 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +    const arr = data?.split(',').map(val => castingMap.cast(type, val)) || []
is the array value will always come as a string with comma as the delimiter? I'm not sure that you can count on it

2022-11-06 12:32 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +    return dataViewFields.reduce((prev, curr) => {
reduce is used for converting a array to object, if you wish to remain with an array, use map instead

2022-11-06 12:38 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +  async reformatArrayFields(){
this function is extremly compilicated, I'm not sure if I understand why do you need it. If I understand correctly you are filtering the same object twice

2022-11-06 12:41 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +      if(!arrayFieldsMap.has(field.FieldID)){
how do you ensure not to overwrite other fields in the data view? you are changing the layout only for the 'Array' fields

2022-11-06 12:47 UTC, roiaharon-pepperi commented on client-side/src/app/services/utilities-service.ts
> +    isDataViewFieldOfPrimitiveTypeArray(){
what is this function? where do you use it?

2022-11-06 12:51 UTC, roiaharon-pepperi requested changes
Please review the comments I wrote, and make changes accordingly

2022-11-07 13:12 UTC, Chasky-H commented
PRs for issues in RL 0.7 should be to upstream branch named v0.7
We need to leave the main branch clean for fixed to v0.6

2022-11-23 21:26 UTC, closed without merging