Populate generic list fields from cards
Pepperi-Addons/resource-list pull request #8
Opened 2022-04-06 13:39 UTC by michaelatias

FYI KeyValuePair object from ngx-lib is not working with pep-select.

2022-04-07 11:30 UTC, roiaharon-pepperi requested changes
there are some issues that are recurring:
- functions with single lines that only have 1 reference needs to be removed.
- try and use the correct types whenever you can
- each title or string in the components need to come from translations file

2022-04-07 11:30 UTC, roiaharon-pepperi commented on client-side/src/app/draggable-card-fields/draggable-card-fields.module.ts
> +        TranslateModule.forChild({
this is outdated, look at other modules you have and copy from there.

2022-04-07 11:30 UTC, roiaharon-pepperi commented on client-side/src/app/draggable-card-fields/draggable-card-fields.module.ts
> +export class DraggableCardFieldsModule { }
you need to initialize the default language for the translations to work

2022-04-07 11:30 UTC, roiaharon-pepperi commented on client-side/src/app/draggable-card-fields/draggable-card-fields.component.ts
> +    this.title = event.card?.currentValue? event.card.currentValue : this.card
you are overriding the title twice. did you mean card?

2022-04-07 11:30 UTC, roiaharon-pepperi commented on client-side/src/app/draggable-card-fields/draggable-card-fields.component.ts
> +    const value = key.indexOf('image') > -1 && key.indexOf('src') > -1 ? event.fileStr :  event && event.source && event.source.key ? event.source.key : event && event.source && event.source.value ?
you are checking for the existence of event & event.source on the 'key', no need to check it again on value. 
any how, split it to multiple lines because it's very unclear

2022-04-07 11:30 UTC, roiaharon-pepperi commented on client-side/src/app/type-map.ts
> +        return result? result: "DateViewFieldType"
what will happen if the type of the field will be "DataViewFieldType"?

2022-04-07 11:30 UTC, roiaharon-pepperi commented on server-side/api.ts
> +        throw new Error('collection name must be exist in request body, instead request query =  ' + request.query);
in the error, change 'body' to 'query'

2022-04-07 11:30 UTC, roiaharon-pepperi commented on server-side/my.service.ts
> +        return this.papiClient.get(`/user_defined_collections/${collectionName}`)
change to 
this.utilities.papiClient.userDefinedCollections.documents(collectionName).find()

2022-04-07 11:46 UTC, michaelatias commented on client-side/src/app/block-editor/block-editor.component.scss
> +    pep-checkbox{
thats not a formal component of ngx-lib. right now i need to use it like Avner did, and that whats he did.

2022-04-07 12:40 UTC, michaelatias commented on client-side/src/app/block-editor/block-editor.component.ts
> +            this.resource = this.resources?.length > 0? this.resources[0] : undefined
nothing should happen, but that happen on ngoninit, and ngoninit run everytime you go into the pages addon, so in order to avid errors i first check if there is any resource

2022-04-12 12:00 UTC, roiaharon-pepperi approved these changes

2022-04-12 12:16 UTC, merged