Refactor generic view
Pepperi-Addons/resource-list pull request #93
Opened 2022-11-21 07:22 UTC by michaelatias

2022-11-21 10:10 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer-data-source.ts
> +        }
Add else instead of return twice

2022-11-21 10:11 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer-data-source.ts
> +        this.items.push({...item, Key: uuid.v4()})
why do you need a key for the item? where do you use it?

2022-11-21 10:14 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer-data-source.ts
> +        if(index < 0){
why do you need to check the existance of the item? isn't it redundant?

2022-11-22 08:43 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/contained-resource-array-field/contained-resource-array-field.component.ts
> +      this.event.asObservable().subscribe((obj) => {
why do you need this event? what is it stands for? this is unclear

2022-11-22 09:04 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +    const newDataSource = this.crateListDataSource()
these 2 lines are always come together. you should add those to a function named 'loadList' or something and call it.

2022-11-22 09:06 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +    actions.push(
you shouldn't manipulate the incoming parameter. instead return an array of actions, and set it to the 'actions' object on the caller

2022-11-22 09:08 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/primitive-array-field/primitive-array-field.component.ts
> +    const typeMap = new TypeMap()
instead of creating a Typemap every time you need it, create once on the constructor and use a class member instead. 
I would even suggest that the typeMap will be a static class with the method get

2022-11-22 09:09 UTC, roiaharon-pepperi commented on client-side/src/app/block/block.component.ts
> +      private utilitiesService: UtilitiesService) {}
why do you need the utilities service?

2022-11-22 09:14 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +  async reformatFields(){
as I told you before, all the functions regarding the formating and manipulation on the data view should be moved to an outer service. this does not belong to this component.

2022-11-22 10:25 UTC, roiaharon-pepperi requested changes

2022-11-22 10:25 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/generic-viewer.component.ts
>      async initRecycleBin(){
recycle bin should be a parameter on the query string, you shouldn't have to do all of that when cycling between recycle bin and list modes. there is 'hidden' property on the menu items that you can use to hide it on 'list' mode. you can look at the UDC for reference

2022-11-22 10:25 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/generic-viewer.component.ts
> +              const item = (await this.genericViewerDataSource.getDeletedItems()).find(item => item.Key == selectedRows.rows[0])
why do you need to get the items from the server? you should have the items in the dataSource

2022-11-22 10:25 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/generic-viewer.component.ts
> +      console.log(`cancel clicked so your code works !!!!`);
remove this debug log

2022-11-22 10:25 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/generic-viewer.model.ts
> +    button: GVButton
button should be a list, with title & key.

2022-11-22 10:25 UTC, roiaharon-pepperi commented on client-side/src/app/services/utilities-service.ts
> +    isDataViewFieldOfPrimitiveTypeArray(){
remove this empty function

2022-11-22 10:25 UTC, roiaharon-pepperi commented on client-side/src/app/views-and-editors/table/table.component.html
> +            noDataFoundMsg = "No Data Found"
what is the difference between this component and the list component? why can't they be the same component?

2022-11-22 10:25 UTC, roiaharon-pepperi commented on shared/entities.ts
> +  export const ARRAY_TYPE = "Array"
you shouldn't have these const variables. you should work with typed objects, and than you won't need it

2022-11-23 09:24 UTC, michaelatias commented on client-side/src/app/generic-viewer/list/list.component.html
> +        <pep-select *ngIf="listOptions.dropDownOfViews.length > 1"
not that I know about such component, the pep select will be visible even when the dropdown will be an empty array

2022-11-23 09:26 UTC, michaelatias commented on client-side/src/app/generic-viewer/list/list.component.ts
> +  @Input() genericViewer: IGenericViewer
I will get rid of it in the future, its just for now I'm using it inside the html

2022-11-23 09:27 UTC, michaelatias commented on client-side/src/app/generic-viewer/list/list.component.ts
> +    this.buttonClickedEvent.emit(this.genericList.getSelectedItems()?.rows || [])
because in case of selection list, we should send all the item that were selected, if its not a selection list then the generic view who used that list component just don't care about that input.

2022-11-23 11:43 UTC, michaelatias commented on client-side/src/app/array-fields/contained-resource-array-field/contained-resource-array-field.component.ts
> +      this.event.asObservable().subscribe((obj) => {
basically I need a way to implement paren child communication, because when the user press update, the editor component needs to data that was edited by the contained resource array component

2022-11-23 11:44 UTC, michaelatias commented on client-side/src/app/field-editor/field-editor.component.ts
> +  async reformatFields(){
I agree, but I will do that in the future(when I will refactoring this component)

2022-11-23 19:05 UTC, roiaharon-pepperi commented on client-side/src/app/array-fields/contained-resource-array-field/contained-resource-array-field.component.ts
> +      this.event.asObservable().subscribe((obj) => {
this logic shouldn't be on the child component. the child is merely UI component with no logic in it. every edit to the data should be on the parent component

2022-11-23 19:09 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/list/list.component.ts
> +    this.buttonClickedEvent.emit(this.genericList.getSelectedItems()?.rows || [])
expose a function on the list component that will return all the selected items. then the selection list could get it using this function

2022-11-23 19:14 UTC, roiaharon-pepperi requested changes

2022-11-23 19:17 UTC, michaelatias commented on client-side/src/app/generic-viewer/list/list.component.ts
> +    this.buttonClickedEvent.emit(this.genericList.getSelectedItems()?.rows || [])
I did it, it's called getSelectedRows

2022-11-23 19:39 UTC, roiaharon-pepperi approved these changes

2022-11-23 19:39 UTC, merged