Extract selection list from generic viewer
Pepperi-Addons/resource-list pull request #97
Opened 2022-11-24 13:38 UTC by michaelatias

2022-11-24 14:33 UTC, roiaharon-pepperi requested changes
I didn't see that you changes the Addon Block relation to open the new component. this is crucial

2022-11-24 14:33 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/selection-list/selection-list.component.ts
> +    this.dialogRef?.close(rows)
you shouldn't close the dialog yourself.. you should be agnostic to the way you're used

2022-11-29 06:08 UTC, roiaharon-pepperi requested changes

2022-11-29 06:08 UTC, roiaharon-pepperi commented on client-side/src/app/field-editor/field-editor.component.ts
> +    dialogRef.componentInstance.pressedCancelEvent.subscribe(() => dialogRef.close() )
what will happen if you'll change the event name on the selectionList component? will this fail at compilation time?

2022-11-29 06:08 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer-data-source.ts
> +        if(this.fields){
please reverse the if statement, and avoid returning in the middle of the function

2022-11-29 06:08 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/selection-list/selection-list.component.ts
> +  onButtonClicked(event){
this should be outside of the component. you shouldn't be aware of the button's key that you got.
you should have only buttonPressed event and the button key should be part of it

2022-11-29 08:22 UTC, michaelatias commented on client-side/src/app/field-editor/field-editor.component.ts
> +    dialogRef.componentInstance.pressedCancelEvent.subscribe(() => dialogRef.close() )
the only solution I can think of is that i will create a function getEvent in the SelectionListComponent which will return the events and their keys , and then I'll subscribe to them.
another possible solution is to send the event emitter as an input to the dialog, but this will be ugly because if you don't open thats component as dialog you dont pass the event emitter as input.

2022-11-29 08:23 UTC, michaelatias commented on client-side/src/app/generic-viewer/selection-list/selection-list.component.ts
> +  onButtonClicked(event){
no because this is the selection list component and that component decide which button the *list component* will display.
the list component doesn't know which button is clicked, and just send event button was clicked with the id of the button

2022-11-29 08:34 UTC, roiaharon-pepperi commented on client-side/src/app/generic-viewer/selection-list/selection-list.component.ts
> +  onButtonClicked(event){
ok, cool

2022-11-29 08:43 UTC, roiaharon-pepperi approved these changes

2022-11-29 08:43 UTC, merged